/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuCategory {
  'id' : bigint,
  'name' : string,
  'itemIds' : Array<bigint>,
}
export interface MenuData {
  'categories' : Array<MenuCategory>,
  'items' : Array<MenuItem>,
}
export interface MenuItem {
  'id' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'description' : string,
  'price' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, Array<bigint>], bigint>,
  'addMenuItem' : ActorMethod<[MenuItem], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenu' : ActorMethod<[], MenuData>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[bigint, string, Array<bigint>], undefined>,
  'updateMenu' : ActorMethod<[MenuData], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];